module.exports = {
    names : [
        "Seen Too Much",
        "Broken Zanti",
        "Living On The Edge",
        "Wild Thing",
        "Wild Thing Edge",
        "The Click",
        "Zapata",
        "Blue Zinger",
        "Petting Zoo",
        "Red Tide",
        "Rollerball",
        "Single Track",
        "Plate Shift",
        "Morning Zanti",
        "Bid Stuffer",
        "Early Discovery",
        "Fred",
        "Wading Pool",
        "The Search",
        "The Blue Bidder",
        "From Above",
        "From Below",
        "The Beach",
        "Zanti Mahem 1",
        "Zanti Mahem 2",
        "Zanti Mahem 3",
        "The Abyss",
        "Junior",
        "Detox",
        "Low Tide",
        "The Zanti Misfit",
        "Ground Strike",
        "The Green Hornet",
        "One Ping Only",
        "The Morphing",
        "Early Riser",
        "The Deep",
        "The Circus Comes to Town",
        "Back To School",
        "The Bagman",
        "Batastic",
        "Faster Zapper",
        "Warp 15",
        "Spastic BAT",
        "The Spartan",
        "Cherokee Nation",
        "Apollo",
        "Orange Marmalade",
        "The Rover",
        "Fuzzy Orange",
        "Marco Polo",
        "Blue Ice",
        "Gone Fishing",
        "Beyond the Blue Wall",
        "Take Two",
        "Changing Tide",
        "Yellow Snow",
        "Zapper Clone",
        "Bristles",
        "Market Share",
        "Blue Stubble",
        "Street Lamps",
        "Blue Flicker",
        "Clogged Artery",
        "Zappa Street",
        "T1 Killer",
        "Search Bots",
        "Pinger",
        "BAT Fence",
        "The Seekers",
        "The Drowning",
        "Wake Up Call",
        "No Joy",
        "Zero to Sixty",
        "Crazy Eyes",
        "Shades of Blue",
        "When the Levee Breaks",
        "Cancelled Check",
        "Quota Machine",
        "Just Ask",
        "Platform Drilling",
        "Dinosaur Hunt",
        "The Green Flash",
        "Rougue Wave",
        "Frog Pond",
        "Power Tower",
        "BAT Discovery",
        "BAT Hats",
        "The Shredder",
        "Obstructus Maximus",
        "Obstructus Maximus 2",
        "Robot Fight",
        "BAT Horizon",
        "Railway",
        "Red Sky at Night",
        "Bot Town",
        "Broken SKY",
        "Life and Death",
        "Sea of BATS",
        "Sea of BATS Star",
        "Buckaroo Banzai",
        "Enchanted Forest",
        "Blockhead",
        "Botastic",
        "Blue Blind",
        "The Bunker",
        "Rock Star",
        "The Outer Limits",
        "The Tickler",
        "Meteors",
        "The Palace",
        "Full Moon Rising",
        "Quota Catcher",
        "Good Luck Human",
        "Simple BAT",
        "Solar Flare",
        "Pacific Rim",
        "Blue Blaster",
        "Mainframe",
        "BAT Code",
        "Made in America",
        "The Thin Blue Line",
        "Thin Blue Line",
        "Blast This",
        "Test Pattern",
        "Scofflaw",
        "The Quota",
        "The Bird",
        "BAT Dribble",
        "The Port",
        "Day Trippin",
        "Master Blaster",
        "EPIC Zapper",
        "The Dead Pool",
        "Penny Pincher",
        "Broken BAT",
        "Gold Finger",
        "The Raceway",
        "Danger Will Robinson",
        "Blue Blocker",
        "City Of BATS",
        "Jump Shot",
        "High Tide",
        "Inner Chart",
        "No Reason",
        "Sea Level",
        "The Deer Hunter",
        "The Pepsi Challenge",
        "Seizure",
        "Local Dump",
        "Repeater Wars",
        "Control Tower",
        "BAT Lego",
        "Lightning Strike",
        "Them",
        "Continental Crust II",
        "Heart Attack",
        "Almost Human",
        "The Follower",
        "Social Butterfly",
        "High EQ",
        "The Ramp",
        "Focus",
        "Hairline",
        "Algo Mountains",
        "Bot Wars",
        "Orange Crush",
        "The Carnival",
        "Bat Pig",
        "Bankers Blitz",
        "Soylent Blue",
        "Cannons",
        "Cannons 2",
        "Clockwork Orange",
        "Clockwork Orange 2",
        "Yellow Picket Fence",
        "The Awakening",
        "Robot Hunting",
        "NARA Zapper",
        "The Blue Pig",
        "CancelBot",
        "Monster Mash",
        "The Monster 2",
        "The Monster",
        "Tank Tracks",
        "Runaway",
        "Eraser Head",
        "The Bridge",
        "Continental Crust",
        "Power Line",
        "Blue Thicket",
        "Broken Highway",
        "Dirty Glaciers",
        "Boston Zapper III",
        "Landmine",
        "BBOBomber",
        "Redline",
        "Twilight",
        "Boston Zapper II",
        "Boston Zapper",
        "Blue Wave",
        "Castle Wall",
        "The Waste Pool",
        "Waste Pool",
        "The Bug",
        "Depth Ping",
        "City Under Siege",
        "Bluegrass",
        "Sunshowers",
        "The Flood",
        "Scissors",
        "Boston Shuffle",
        "BAT Cave",
        "BOTvsBOT",
        "Flag Repeater",
        "The Crown",
        "Batsicles",
        "Blotter",
        "Stubby Triangles",
        "Flutter",
        "Periscopes",
        "Double Dip",
        "Racing Stripe",
        "Puzzle Pieces",
        "Blue Bandsaw",
        "Ask Mountain"
    ]
};